from __future__ import annotations

from typing import Protocol


class LLMClient(Protocol):
    def generate_json(self, *, system_prompt: str, user_payload: dict) -> dict:
        """Return a JSON-compatible dict generated by the model."""


class NotConfiguredLLMClient:
    def generate_json(self, *, system_prompt: str, user_payload: dict) -> dict:
        raise RuntimeError("LLM client is not configured yet. Wire Claude Agent SDK or another provider here.")
