export const stepLabels: Record<string, string> = {
  ingest_source: "读取来源材料",
  build_source_manifest: "确认材料范围",
  build_story_bible: "生成故事圣经",
  review_volume_fit: "检查内容体量",
  split_episodes: "规划拆集",
  build_material_bank: "整理素材库",
  build_story_seed: "生成故事种子",
  build_series_blueprint: "生成系列蓝图",
  build_episode_cards: "生成分集规划",
  extract_video_scripts: "逐集还原视频剧本",
  aggregate_reference_scripts: "汇总参考剧本",
  analyze_reference_scripts: "分析参考剧本",
  propose_adaptation_options: "生成改编方案",
  build_adaptation_brief: "生成改编 Brief",
	generate_continuation_options: "生成续写方向",
	generate_continuation_script: "生成续写剧本",
  build_script_contexts: "准备单集生成上下文",
  generate_script_units: "生成单集剧本",
  review_script_set: "审核完整剧本",
  aggregate_scripts: "汇总完整剧本",
};
